# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", ip: "192.168.250.10"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu2004_mno_001"
    vb.memory = "2048"
    vb.cpus = 2
  end
end
